module.exports = {
    GET_DEPARTMENT_SALES_SETUP_LIST : 'GET_DEPARTMENT_SALESSETUP_LIST',
    GET_DEPARTMENT_SALESSETUP_LIST_SUCCESS : 'GET_DEPARTMENT_SALESSETUP_LIST_SUCCESS',
    
    INSERT_UPDATE_DEPT_SALES_SETUP : 'INSERT_UPDATE_DEPT_SALES_SETUP',
    INSERT_UPDATE_DEPT_SALES_SETUP_SUCCESS : 'INSERT_UPDATE_DEPT_SALES_SETUP_SUCCESS',
    INSERT_UPDATE_DEPT_SALES_SETUP_ERROR : 'INSERT_UPDATE_DEPT_SALES_SETUP_ERROR',

    UPDATE_DEPT_SALES_SETUP_SUCCESS : 'UPDATE_DEPT_SALES_SETUP_SUCCESS',
    UPDATE_DEPT_SALES_SETUP_ERROR : 'UPDATE_DEPT_SALES_SETUP_ERROR',

    DELETE_DEPT_SALES_SETUP : 'DELETE_DEPT_SALES_SETUP',
    DELETE_DEPT_SALES_SETUP_SUCCESS : 'DELETE_DEPT_SALES_SETUP_SUCCESS',
    DELETE_DEPT_SALES_SETUP_ERROR : 'DELETE_DEPT_SALES_SETUP_ERROR',
    
    GET_MAJOR_CLASS_FILTER : 'GET_MAJOR_CLASS_FILTER',
    GET_MAJOR_CLASS_FILTER_SUCCESS : 'GET_MAJOR_CLASS_FILTER_SUCCESS',
    
    GET_LIKE_MAJOR_CLASS_FILTER : 'GET_LIKE_MAJOR_CLASS_FILTER',
    GET_LIKE_MAJOR_CLASS_FILTER_SUCCESS : 'GET_LIKE_MAJOR_CLASS_FILTER_SUCCESS',
    
    GET_SUB_CLASS_FILTER : 'GET_SUB_CLASS_FILTER',
    GET_SUB_CLASS_FILTER_SUCCESS : 'GET_SUB_CLASS_FILTER_SUCCESS',
    
    GET_LIKE_SUB_CLASS_FILTER : 'GET_LIKE_SUB_CLASS_FILTER',
    GET_LIKE_SUB_CLASS_FILTER_SUCCESS : 'GET_LIKE_SUB_CLASS_FILTER_SUCCESS',

    GET_DEPARTMENT_FILTER : 'GET_DEPARTMENT_FILTER',
    GET_DEPARTMENT_FILTER_SUCCESS : 'GET_DEPARTMENT_FILTER_SUCCESS',

    GET_LIKE_DEPARTMENT_FILTER : 'GET_LIKE_DEPARTMENT_FILTER',
    GET_LIKE_DEPARTMENT_FILTER_SUCCESS : 'GET_LIKE_DEPARTMENT_FILTER_SUCCESS',

    GET_UPDATE_LIKE_MAJOR_CLASS_FILTER: 'GET_UPDATE_LIKE_MAJOR_CLASS_FILTER',
    GET_UPDATE_LIKE_MAJOR_CLASS_FILTER_SUCCESS: 'GET_UPDATE_LIKE_MAJOR_CLASS_FILTER_SUCCESS',

    GET_UPDATE_LIKE_SUB_CLASS_FILTER: 'GET_UPDATE_LIKE_SUB_CLASS_FILTER',
    GET_UPDATE_LIKE_SUB_CLASS_FILTER_SUCCESS: 'GET_UPDATE_LIKE_SUB_CLASS_FILTER_SUCCESS',

    ONCHANGE_DEPARTMENT: 'ONCHANGE_DEPARTMENT',
    ONCHANGE_MAJOR_CLASS: 'ONCHANGE_MAJOR_CLASS',
    ONCHANGE_SUB_CLASS: 'ONCHANGE_SUB_CLASS',

    ONCHANGE_LIKE_DEPARTMENT: 'ONCHANGE_LIKE_DEPARTMENT',
    ONCHANGE_LIKE_MAJOR_CLASS: 'ONCHANGE_LIKE_MAJOR_CLASS',
    ONCHANGE_LIKE_SUB_CLASS: 'ONCHANGE_LIKE_SUB_CLASS',

    SET_STATE: 'SET_STATE',
    FILTER: 'FILTER',
    ON_CAPACITY_CLICKED: 'ON_CAPACITY_CLICKED',
    ON_CAPACITY_CHANGED: 'ON_CAPACITY_CHANGED',
    ON_LIKE_MAJOR_CLASS_CLICK: 'ON_LIKE_MAJOR_CLASS_CLICK',
    ON_LIKE_MAJOR_CLASS_UPDATE: 'ON_LIKE_MAJOR_CLASS_UPDATE',
    ON_LIKE_SUB_CLASS_CLICK: 'ON_LIKE_SUB_CLASS_CLICK',
    ON_LIKE_SUB_CLASS_UPDATE: 'ON_LIKE_SUB_CLASS_UPDATE',
    CHANGE_PO_FREEZE_DATE: 'CHANGE_PO_FREEZE_DATE',
    ON_BEGIN_DATE_CLICK: 'ON_BEGIN_DATE_CLICK',
    ON_CHANGE_END_DATE: 'ON_CHANGE_END_DATE',
    ON_END_DATE_CLICK: 'ON_END_DATE_CLICK',
    UPDATE_SAVE_COMPONENT: 'UPDATE_SAVE_COMPONENT',
    UPDATE_INSERT_ERROR: 'UPDATE_INSERT_ERROR',
    UPDATE_INSERT_ERROR_SUCCESS: 'UPDATE_INSERT_ERROR_SUCCESS',
    SORT_DATA: 'SORT_DATA',

    RESET_ERROR_MSG: 'RESET_ERROR_MSG',
    RETRIVE_SALES_ERROR: 'RETRIVE_SALES_ERROR'
}